package com.jeff.model;
// Generated 2017-3-25 10:43:49 by Hibernate Tools 4.3.5.Final

/**
 * Bridge generated by hbm2java
 */
public class Bridge implements java.io.Serializable {

	private Integer id;
	private String univCode;
	private String majorCode;
	private String year;
	private String xueyuan;

	public Bridge() {
	}

	public Bridge(String univCode, String majorCode, String year) {
		this.univCode = univCode;
		this.majorCode = majorCode;
		this.year = year;
	}

	public Bridge(String univCode, String majorCode, String year, String xueyuan) {
		this.univCode = univCode;
		this.majorCode = majorCode;
		this.year = year;
		this.xueyuan = xueyuan;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUnivCode() {
		return this.univCode;
	}

	public void setUnivCode(String univCode) {
		this.univCode = univCode;
	}

	public String getMajorCode() {
		return this.majorCode;
	}

	public void setMajorCode(String majorCode) {
		this.majorCode = majorCode;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getXueyuan() {
		return this.xueyuan;
	}

	public void setXueyuan(String xueyuan) {
		this.xueyuan = xueyuan;
	}

}
