package com.jeff.model;
// Generated 2017-3-25 10:43:49 by Hibernate Tools 4.3.5.Final

/**
 * CollegeScoreLine generated by hbm2java
 */
public class CollegeScoreLine implements java.io.Serializable {

	private Integer id;
	private String univCode;
	private String univName;
	private String province;
	private String artsScience;
	private String year;
	private String batch;
	private String averageScore;
	private String highestScore;
	private String lowestScore;
	private Integer num;
	private String fencha;
	private String provinceScore;

	public CollegeScoreLine() {
	}

	public CollegeScoreLine(String univCode, String univName, String province, String artsScience, String year,
			String batch, String averageScore, String highestScore, String lowestScore, Integer num, String fencha,
			String provinceScore) {
		this.univCode = univCode;
		this.univName = univName;
		this.province = province;
		this.artsScience = artsScience;
		this.year = year;
		this.batch = batch;
		this.averageScore = averageScore;
		this.highestScore = highestScore;
		this.lowestScore = lowestScore;
		this.num = num;
		this.fencha = fencha;
		this.provinceScore = provinceScore;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUnivCode() {
		return this.univCode;
	}

	public void setUnivCode(String univCode) {
		this.univCode = univCode;
	}

	public String getUnivName() {
		return this.univName;
	}

	public void setUnivName(String univName) {
		this.univName = univName;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getArtsScience() {
		return this.artsScience;
	}

	public void setArtsScience(String artsScience) {
		this.artsScience = artsScience;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	public String getAverageScore() {
		return this.averageScore;
	}

	public void setAverageScore(String averageScore) {
		this.averageScore = averageScore;
	}

	public String getHighestScore() {
		return this.highestScore;
	}

	public void setHighestScore(String highestScore) {
		this.highestScore = highestScore;
	}

	public String getLowestScore() {
		return this.lowestScore;
	}

	public void setLowestScore(String lowestScore) {
		this.lowestScore = lowestScore;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getFencha() {
		return this.fencha;
	}

	public void setFencha(String fencha) {
		this.fencha = fencha;
	}

	public String getProvinceScore() {
		return this.provinceScore;
	}

	public void setProvinceScore(String provinceScore) {
		this.provinceScore = provinceScore;
	}

}
