package com.jeff.model;
// Generated 2017-3-25 10:43:49 by Hibernate Tools 4.3.5.Final

/**
 * Dis generated by hbm2java
 */
public class Dis implements java.io.Serializable {

	private String disCode;
	private String disName;
	private String disIntro;
	private String disAim;

	public Dis() {
	}

	public Dis(String disCode) {
		this.disCode = disCode;
	}

	public Dis(String disCode, String disName, String disIntro, String disAim) {
		this.disCode = disCode;
		this.disName = disName;
		this.disIntro = disIntro;
		this.disAim = disAim;
	}

	public String getDisCode() {
		return this.disCode;
	}

	public void setDisCode(String disCode) {
		this.disCode = disCode;
	}

	public String getDisName() {
		return this.disName;
	}

	public void setDisName(String disName) {
		this.disName = disName;
	}

	public String getDisIntro() {
		return this.disIntro;
	}

	public void setDisIntro(String disIntro) {
		this.disIntro = disIntro;
	}

	public String getDisAim() {
		return this.disAim;
	}

	public void setDisAim(String disAim) {
		this.disAim = disAim;
	}

	@Override
	public String toString() {
		return "Dis [disCode=" + disCode + ", disName=" + disName + ", disIntro=" + disIntro + ", disAim=" + disAim
				+ "]";
	}

}
