package com.jeff.model;
// Generated 2017-3-25 10:43:49 by Hibernate Tools 4.3.5.Final

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer newsId;
	private String newsTitle;
	private String newsDate;
	private String newsContent;
	private String newsLabel;
	private String hot;

	public News() {
	}

	public News(String newsTitle, String newsDate, String newsContent, String newsLabel, String hot) {
		this.newsTitle = newsTitle;
		this.newsDate = newsDate;
		this.newsContent = newsContent;
		this.newsLabel = newsLabel;
		this.hot = hot;
	}

	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public String getNewsDate() {
		return this.newsDate;
	}

	public void setNewsDate(String newsDate) {
		this.newsDate = newsDate;
	}

	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	public String getNewsLabel() {
		return this.newsLabel;
	}

	public void setNewsLabel(String newsLabel) {
		this.newsLabel = newsLabel;
	}

	public String getHot() {
		return this.hot;
	}

	public void setHot(String hot) {
		this.hot = hot;
	}

}
