package com.jeff.model;
// Generated 2017-3-25 10:43:49 by Hibernate Tools 4.3.5.Final

/**
 * Rank12 generated by hbm2java
 */
public class Rank12 implements java.io.Serializable {

	private Integer id;
	private String specCode;
	private String specName;
	private String univCode;
	private String univName;
	private String univScore;
	private String univRank;

	public Rank12() {
	}

	public Rank12(String specCode, String specName, String univCode, String univName, String univScore,
			String univRank) {
		this.specCode = specCode;
		this.specName = specName;
		this.univCode = univCode;
		this.univName = univName;
		this.univScore = univScore;
		this.univRank = univRank;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSpecCode() {
		return this.specCode;
	}

	public void setSpecCode(String specCode) {
		this.specCode = specCode;
	}

	public String getSpecName() {
		return this.specName;
	}

	public void setSpecName(String specName) {
		this.specName = specName;
	}

	public String getUnivCode() {
		return this.univCode;
	}

	public void setUnivCode(String univCode) {
		this.univCode = univCode;
	}

	public String getUnivName() {
		return this.univName;
	}

	public void setUnivName(String univName) {
		this.univName = univName;
	}

	public String getUnivScore() {
		return this.univScore;
	}

	public void setUnivScore(String univScore) {
		this.univScore = univScore;
	}

	public String getUnivRank() {
		return this.univRank;
	}

	public void setUnivRank(String univRank) {
		this.univRank = univRank;
	}

}
